baseURL = "https://www.alexlwyen.com/"
languageCode = "en-us"
title = "Alex Yen"
theme = "soho"

enableInlineShortcodes = true

summarylength = 10
enableEmoji = true

[params]
author = "Alex Yen"
pronouns = "(he/him/his)"
description = "Email: alyen@ucsd.edu"
google_analytics_id="UA-132398315-1"

## Set one of:
# gravatar = "soho@example.com"
profilePicture = "images/yen_website.jpg"

copyright = "Alex Yen"
##license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

## Set custom CSS and/or JS to override site defaults.
customCss = ["css/website.css"]
customJs = ["js/website.js"]

  ## Set as many as you want.
#  [[params.socialIcons]]
#  icon = "fa-linkedin"
#  title = "Linkedin"
#  url = "https://www.linkedin.com/in/alex-lw-yen"

#  [[params.socialIcons]]
#  icon = "fa-github"
#  title = "GitHub"
#  url = "https://github.com/alwyen"
  
#  [[params.socialIcons]]
#  icon = "ai-google-scholar-square"
#  title = "GoogleScholar"
#  url = "https://scholar.google.com/citations?user=F8lPEiIAAAAJ&hl=en"

[menu]

  [[menu.main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

  [[menu.main]]
  name = "Google Scholar"
  weight = 400
  url = "https://scholar.google.com/citations?user=F8lPEiIAAAAJ&hl=en"

  [[menu.main]]
  name = "GRFP Content"
  weight = 450
  identifier = "grfp"
  url = "/grfp_content/"

  [[menu.main]]
  name = "Misc"
  weight = 500
  identifier = "misc"
  url = "/misc/"

  [[menu.main]]
  name = "CV"
  weight = 600
  identifier = "CV"
  url = "https://www.alexlwyen.com/CV/yen_cv.pdf"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true